In [1]:
doc1 = "breakthrough drug for schizophrenia"
doc2 = "new schizophrenia drug"
doc3 = "new approach for treatment of schizophrenia"
doc4 = "new hopes for schizophrenia patients"

In [2]:
docs = [doc1,doc2,doc3,doc4]
docs

['breakthrough drug for schizophrenia',
 'new schizophrenia drug',
 'new approach for treatment of schizophrenia',
 'new hopes for schizophrenia patients']

In [3]:
#Finding unique terms

unique=set()
for doc in docs:
  for term in doc.split():
    unique.add(term)
unique

{'approach',
 'breakthrough',
 'drug',
 'for',
 'hopes',
 'new',
 'of',
 'patients',
 'schizophrenia',
 'treatment'}

In [7]:
# Constructing a term-document matrix. Here it is done as a dictionary for the ease of interpretability

term_doc_mat = {}

for term in unique:
  term_doc_mat[term]=[]

  for doc in docs:
    if term in doc:
      term_doc_mat[term].append(1)
    else:
      term_doc_mat[term].append(0)  

In [9]:
term_doc_mat

{'approach': [0, 0, 1, 0],
 'breakthrough': [1, 0, 0, 0],
 'drug': [1, 1, 0, 0],
 'for': [1, 0, 1, 1],
 'hopes': [0, 0, 0, 1],
 'new': [0, 1, 1, 1],
 'of': [0, 0, 1, 0],
 'patients': [0, 0, 0, 1],
 'schizophrenia': [1, 1, 1, 1],
 'treatment': [0, 0, 1, 0]}

In [32]:
# to find all documents that contain 'drug' and 'schizophrenia' 

import numpy as np
docs_array = np.array(docs,dtype='object')

d = np.array(term_doc_mat['drug'])
s = np.array(term_doc_mat['schizophrenia'])

print(d)
print(s)

print('---------')
intersection = d&s 
print(intersection)

[1 1 0 0]
[1 1 1 1]
---------
[1 1 0 0]


In [33]:
# Getting the matching documents 

match=[]
for doc in intersection*docs_array:
  if doc :
    match.append(doc)
match    

['breakthrough drug for schizophrenia', 'new schizophrenia drug']

In [34]:
# to find documents containing 'drug' or 'approach'

D = np.array(term_doc_mat['drug'])
A = np.array(term_doc_mat['approach'])
union = D | A

print(D)
print(A)

print('---------')

print(union)

[1 1 0 0]
[0 0 1 0]
---------
[1 1 1 0]


In [35]:
# Getting the matching documents

Match = []
for doc in union*docs_array:
  if doc:
    Match.append(doc)
Match    

['breakthrough drug for schizophrenia',
 'new schizophrenia drug',
 'new approach for treatment of schizophrenia']